import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  nelbiaquests: [{type: 'autogenerated', dirName: 'nelbiaquests'}],
};

export default sidebars;
